name: CI

on:
  push:
    branches: 
      - master

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # 检出代码
    - uses: actions/checkout@v2

    # 构建镜像
    - name: Build Docker Image
      env:
        DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
      run: |
        docker login registry.cn-hongkong.aliyuncs.com -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
        docker run -v $PWD:/worker registry.cn-hongkong.aliyuncs.com/hehety/digger:latest digger worker -d
